#!/bin/bash

radio=$(cat "$HOME"/.config/wradio/stations | wmenu -Nefefef -n272b2e -M272b2e -mefefef -S272b2e -sefefef -p Station)

if [[ "$radio" == "" ]]; then
  exit
fi
echo $radio | awk -F"|" '{print $2}' | xargs cvlc
