#!/bin/bash

radio=$(cat "$HOME"/.config/wradio/stations | wmenu -Nefefef -n252525 -M252525 -mefefef -S252525 -sefefef -p Station)

if [[ "$radio" == "" ]]; then
  exit
fi
echo $radio | awk -F"|" '{print $2}' | xargs cvlc
